export { default as Header } from './Header/Header'
export { default as NavBar } from './NavBar/NavBar'
export { default as Main } from './Main/Main'
export { default as New } from './New/New'
export { default as Product } from './Product/Product'
export { default as Reviews } from './Reviews/Reviews'
export { default as Gallery } from './Gallery/Gallery'
